### PR TITLE
Added Image classname for styling

### PR DESCRIPTION
**Pull request by meetzaveri**
As of pull request of mediadetails.js this pull request is also necessary for styling the image
#14

### CODE REVIEW

**Comment by imrenagi** [comment]
Thanks for the contribution. but why did you create two different PR for the same issue? I'm just wondering.

**Comment by meetzaveri** [comment]
@imrenagi I a beginner , I know basics of git of pushing, committing, pulling requests and opening of issues. But I was stuck on that how to make two changes in one PR. So if you can guide me down it would be resourceful. Thanks

**Comment by imrenagi** [comment]
It's okay. no worries. So here is how. You need to work on the same branch as your 1st PR. So, just continue working on that branch and commit the changes that you've made in this PR, and your 1st pull request will be updated automatically. Does it make sense? I will invalidate this PR then.

**Comment by imrenagi** [comment]
Notes: This PR is closed because this can be done in another PR instead of create a new one.

**Comment by meetzaveri** [comment]
Yes done ! I worked on that branch dude ! See that commit

**Pull request closed without merging**
